### ISSUE TITLE
群晖启动容器以后意外停止

### ISSUE THREAD

**Issue by zhailala** [MT-Photos/mt-photos-deepface#1]
容器 mt-photos-deepface 意外停止，有群辉的详细操作教程吗？

**Comment by shushuhai924** [comment]
> 容器 mt-photos-deepface 意外停止，有群辉的详细操作教程吗？

同样问题，退出代码132

**Comment by sorakiseki24** [comment]
同问，qnap也是一样的问题

**Comment by tza17313** [comment]
应该是cpu不支持avx的原因，等后面更新吧

**Comment by alumnicn** [comment]
同运行不起,唉

**Comment by GavinGoo** [comment]
试试我的镜像，实测g3930可用：
```
docker pull gavingooo/mt-photos-deepface-noavx:latest
```
```
docker run -id -p 8066:8066 --restart=unless-stopped --name mt-photos-deepface -e TZ=Asia/Shanghai -e API_AUTH_KEY=mt_photos_ai_extra gavingooo/mt-photos-deepface-noavx:latest
```

**Comment by sorakiseki24** [comment]
> 试试我的镜像，实测g3930可用：
> 
> ```
> docker pull gavingooo/mt-photos-deepface-noavx:latest
> ```
> 
> ```
> docker run -id -p 8066:8066 --restart=unless-stopped --name mt-photos-deepface -e TZ=Asia/Shanghai -e API_AUTH_KEY=mt_photos_ai_extra gavingooo/mt-photos-deepface-noavx:latest
> ```

可以正常启动，但是配置API，提示测试不通过。大佬知道什么问题吗？

**Comment by GavinGoo** [comment]
> > 试试我的镜像，实测g3930可用：
> > 
> > ```
> > docker pull gavingooo/mt-photos-deepface-noavx:latest
> > ```
> > 
> > ```
> > docker run -id -p 8066:8066 --restart=unless-stopped --name mt-photos-deepface -e TZ=Asia/Shanghai -e API_AUTH_KEY=mt_photos_ai_extra gavingooo/mt-photos-deepface-noavx:latest
> > ```
> 
> 可以正常启动，但是配置API，提示测试不通过。大佬知道什么问题吗？

确定ip、端口、环境变量API_AUTH_KEY对得上吗？
另外ip得填docker网关，一般是172.17.0.1/172.18.0.1，具体可通过`docker inspect <容器名>`查看

**Comment by sorakiseki24** [comment]
> > > 试试我的镜像，实测g3930可用：
> > > ```
> > > docker pull gavingooo/mt-photos-deepface-noavx:latest
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > docker run -id -p 8066:8066 --restart=unless-stopped --name mt-photos-deepface -e TZ=Asia/Shanghai -e API_AUTH_KEY=mt_photos_ai_extra gavingooo/mt-photos-deepface-noavx:latest
> > > ```
> > 
> > 
> > 可以正常启动，但是配置API，提示测试不通过。大佬知道什么问题吗？
> 
> 确定ip、端口、环境变量API_AUTH_KEY对得上吗？ 另外ip得填docker网关，一般是172.17.0.1/172.18.0.1，具体可通过`docker inspect <容器名>`查看

测试不通过 [object Object]
提示这样的
